all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: root
    ansible_ssh_pass: screencast
    ansible_become: true
    security_mode: kerberos
    install_service: False
preflight:
  hosts:
    zookeeper1:
    zookeeper2:
    zookeeper3:
    kafka1:
    kafka2:
    kafka3:
    c3test01:
zookeeper:
  hosts:
    zookeeper1:
    zookeeper2:
    zookeeper3:
broker:
  hosts:
    kafka1:
      kafka:
        broker:
          id: 1
          config:
            "broker.rack": dc1
    kafka2:
      kafka:
        broker:
          id: 2
          config:
            "broker.rack": dc1 
    kafka3:
      kafka:
        broker:
          id: 3
          config:
            "broker.rack": dc1
control-center:
  hosts:
    c3test01:
